#!/bin/bash

# ./download-video-m3u8 input.m3u8 output.mkv 

ffmpeg -user_agent "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7" -i $1 -c copy $2